### ISSUE TITLE
Restrict to HTML pages

### ISSUE THREAD

**Issue by chocolateboy** [traktofon/cf-detect#3]
The bug was in a HTML parser and [only affected web pages](https://blog.cloudflare.com/incident-report-on-memory-leak-caused-by-cloudflare-parser-bug/#parsingandmodifyinghtmlonthefly), but the addon currently checks headers for all resources.

This results in a non-Cloudflare page like http://stackexchange.com/, which is [not affected](https://github.com/pirate/sites-using-cloudflare/issues/21), being flagged because it includes images from http://stack.imgur.com/, which are behind CF. The same will be true for any pages which include non-HTML resources from a CF-fronted site.

**Comment by traktofon** [comment]
Hi chocolateboy, thanks for the report.

In my understanding, the bug was _triggered_ by the HTML parser (which indeed only processes web pages), but this parser was running as a module for nginx, and the nginx process was also handling other types of requests, so that actually memory related to those requests could be disclosed. As far as I understand [this section](https://blog.cloudflare.com/incident-report-on-memory-leak-caused-by-cloudflare-parser-bug/#externalimpactandcacheclearing) of the CF incident report, plenty of non-HTML data was disclosed.

Example scenario: User requests to load an image from a website behind CF, but needs to send his session token/cookie along to have access to the image (think okcupid). The requested resource is an image, but the request headers might have been leaked through cloudbleed.

The false positives you mention is, in my opinion, a different problem. Namely, if any request in the context of a tab is served by CF, the whole tab is "tainted". In a sense, this is correct: the page **does** use CF because some part of it is using CF. But I agree, this is potentially confusing for the user.

My suggestion is the following:

1. For each tab, bin the requests served by CF by domain.
2. If the tab's primary domain is affected, use red icon. If only 3rd party domains affected, use yellow icon.
3. Show details about affected domains when clicking on the icon.

Let me know if this approach would be acceptable for you.

**Comment by chocolateboy** [comment]
> My suggestion is the following

Sounds good :+1:
