### ISSUE TITLE
A site detected with  Detect Cloudflare 0.2 no longer is with 0.3

### ISSUE THREAD

**Issue by ghost** [traktofon/cf-detect#4]
Hi,

Archive.is was detected with Detect Cloudflare 0.2 but isn't with Detect Cloudflare 0.3 

I first thought that Archive.is had modified its relationships! I then checked Archive.is with testers provided on https://github.com/pirate/sites-using-cloudflare/wiki/List-Search-Tools and all mentioned Archive.is as using CloudFlare.

I haven't reverted to Detection Cloudflare 0.2 to recheck. I'm mentioning this for whatever the developer may consider it pertinent or not.

**Comment by traktofon** [comment]
Hi zymase, thanks for your report. This problem is caused by the new feature to reset the icon when the tab is updated to a new URL. Unfortunately, the current approach is not working very well. Namely, the event of "tab URL has changed" is only sent after the first request has already been processed. And for archive.is, there is only a single request served by CF. This request gets detected, but then the icon is immediately reset. For most pages, there are many requests served by CF, so the detection still works. I probably need to use the webNavigation API instead for handling the tab update.
